name: lochgeo's blog
url: http://lochgeo.github.io
description: Another attempt at a static blog

permalink: /:year/:title/
paginate: 5
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
